# Generated by Django 5.1.4 on 2024-12-23 15:55
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0003_remove_habilidad_usuario_remove_proyecto_usuario_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreProyecto', models.CharField(max_length=300)),
                ('descripcion', models.TextField(max_length=600)),
                ('urlRepositorio', models.URLField(max_length=400)),
                ('fechaCreacion', models.DateField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario')),
            ],
        ),
    ]
