# Generated by Django 5.1.4 on 2024-12-19 16:46
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=300)),
                ('email', models.CharField(max_length=300)),
                ('password', models.CharField(max_length=300)),
                ('descripcion', models.CharField(max_length=500)),
                ('telefono', models.CharField(max_length=20)),
                ('domicilio', models.CharField(max_length=500)),
                ('pais', models.CharField(max_length=50)),
                ('provincia', models.CharField(max_length=50)),
                ('ciudad', models.CharField(max_length=250)),
                ('fechaNacimiento', models.DateField()),
                ('numeroDocumento', models.CharField(max_length=50)),
            ],
        ),
    ]
