# Generated by Django 5.1.4 on 2024-12-23 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_estudio_habilidad_proyecto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habilidad',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='Estudio',
        ),
        migrations.DeleteModel(
            name='Habilidad',
        ),
        migrations.DeleteModel(
            name='Proyecto',
        ),
    ]
